### Login Api
POST http://127.0.0.1:8080/auths/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "password"
}

### Sign up Mock API
POST http://127.0.0.1:8080/signup HTTP/1.1
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "password"
}

### Login Mock API
POST http://127.0.0.1:8080/login HTTP/1.1
Content-Type: application/json

{
  "token": "67ef57264332ec80a29dcb5f86dc2f185758755aa6fce3e373933f9a96634c93",
  "email": "abc@gmail.com"
}

### Get / Mock API
GET http://127.0.0.1:8080 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY0BnbWFpbC5jb20iLCJpYXQiOjE2OTQ0NDY4NTMsImV4cCI6MTc4MDg0Njg1M30.SM5kmI1PfkqYFrr5YJH5HybbWATrYlpnCmIHnJyQVH8

### Forgot Password Mock API
POST http://127.0.0.1:8080/forgetPassword HTTP/1.1
Content-Type: application/json

{
  "email": "abc@gmail.com"
}

### Reset Password
POST http://127.0.0.1:8080/auths/api/resetPassword HTTP/1.1
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "token": "4bad51e56cfc76bcf487ea966607ce3e",
  "newPassword": "password"
}