### Login Api
POST http://127.0.0.1:8080/auths/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "password"
}

### Sign up Mock API
POST http://127.0.0.1:8080/signup HTTP/1.1
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "password"
}

### Login Mock API
POST http://127.0.0.1:8080/login HTTP/1.1
Content-Type: application/json

{
  "token": "34ac64bcb9ca51e14555ee6da858933f2fcdb6ea5290c131d5828c1da4c0b89e",
  "email": "abc@gmail.com"
}

### Get / Mock API
GET http://127.0.0.1:8080 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY0BnbWFpbC5jb20iLCJpYXQiOjE2OTQ0NDY4NTMsImV4cCI6MTc4MDg0Njg1M30.SM5kmI1PfkqYFrr5YJH5HybbWATrYlpnCmIHnJyQVH8

### Forgot Password Mock API
POST http://127.0.0.1:8080/forgetPassword HTTP/1.1
Content-Type: application/json

{
  "email": "abc@gmail.com"
}

### Reset Password
POST http://127.0.0.1:8080/auths/api/resetPassword HTTP/1.1
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "token": "790075da958a5642e8117cf7ff0b37d0",
  "newPassword": "password"
}